apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: my-camel-app
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      backstage.io/kubernetes-id: my-camel-app
      app.kubernetes.io/instance: my-camel-app    